apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: petclinic-production

bases:
  - ../../base

patchesStrategicMerge:
  - patches.yml
  - db-secret-patch.yml # jede Datei muss hier rein!

commonLabels:
  environment: production
